#+TITLE: Lab12 Tests
#+TESTY: PREFIX="lab12"
#+TESTY: REPORT_FRACTION=1
#+TESTY: TIMEOUT=10s
#+TESTY: SHOW=1

* QUIZ: QUESTIONS.txt
This test determines if the answers in QUESTIONS.txt are correct. This
file must be edited so that the correct ( ) choices are replaced with
(X) AND no other changes are made to the file. If you are confident in
your answers but think you may have made inadvertent changes to
QUESTIONS.txt, you can try restoring it with the provided
QUESTIONS.txt.bk file.

The correct output for the test should be
>> ./test_quiz_filter QUESTIONS.txt | sha256sum -C QUESTION.sha256
-: OK

Note: the sha256sum program is used to verify and must be installed to work.

#+TESTY: use_valgrind=0

#+BEGIN_SRC sh
>> ./test_quiz_filter QUESTIONS.txt | sha256sum -c QUESTIONS.sha256
-: OK
#+END_SRC


* CODE threads_main
Checks the threads_main program for correct output. The consumer threads
may get turns in different orders on different executions (hence the
use of 'sed' to elide their indexes), but the queue elements are always
removed in the same order.

#+TESTY: use_valgrind=0
#+BEGIN_SRC sh
>> ./threads_main | sed 's/^Consumer [0-9]/Consumer x/'
Consumer x: Akerman
Consumer x: Blegen
Consumer x: Campbell
Consumer x: Diehl
Consumer x: Eddy
Consumer x: Ford
Consumer x: Gibson
Consumer x: Heller
Consumer x: Iona
Consumer x: Jackson
#+END_SRC

